server:
  port: 8080

ollama:
  base-url: http://localhost:11434
  model: mixtral:8x7b

services:
  jobs:
    base-url: http://localhost:8081

aws:
  backend:
    base-url: https://rosensteininstalaciones.com.ar/api
    service-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyaS1vcmNoZXN0cmF0b3IiLCJyb2xlIjoic2VydmljZSIsInNjb3BlcyI6WyJ1c2VyczpyZWFkIiwic3VjdXJzYWxzOnJlYWQiLCJtYWNoaW5lczpyZWFkIl0sImlhdCI6MTc2Nzg5ODIwMiwiZXhwIjoxOTI1Njg2MjAyfQ.HV6nxjFTd1OVQCeUyNdKiWl4p85E3dKWQlAn9ghH9vo

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
